### ISSUE TITLE
Improve error origin reporting for companion-related errors

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/parity-processbot#351]
Problem: The error from #349  happened due to a parsing error for the description of https://github.com/paritytech/cumulus/pull/870#issue-1084759761, but it was reported on the Substrate PR https://github.com/paritytech/substrate/pull/10463#issuecomment-1005816563 with no way to trace it back to the source of the problem without looking at the logs.

Solution: The error message should include where the error originated from, as in

> Error ...
> While trying to parse the description of https://github.com/paritytech/cumulus/pull/870

**Comment by joao-paulo-parity** [comment]
This might have been fixed by #354

**Comment by mordamax** [comment]
@joao-paulo-parity is that it?

<img width="737" alt="image" src="https://user-images.githubusercontent.com/1177472/173707679-3b90cc9c-51ad-45db-9909-537bbf8219e2.png">

or some other cases still missing for this scope of issue?

**Comment by joao-paulo-parity** [comment]
This one is about a different problem. That being said I think it is working properly now, so it's better to create a new issue in case this comes up again.
